--26/06/2025
--@PLima

--query_obter_pacientes

SELECT 
    APV.NR_ATENDIMENTO
FROM ATENDIMENTO_PACIENTE_V APV
LEFT JOIN prescr_medica PM ON (  PM.NR_ATENDIMENTO = APV.NR_ATENDIMENTO )
LEFT JOIN prescr_mat_hor PH ON ( PH.NR_PRESCRICAO = PM.NR_PRESCRICAO)
WHERE APV.DT_ALTA IS  NULL
And	PH.dt_horario between SYSDATE -1 and SYSDATE
and APV.CD_SETOR_ATENDIMENTO not in (  171 )
GROUP BY 
    APV.NR_ATENDIMENTO,
    APV.CD_SETOR_ATENDIMENTO,
    APV.CD_PESSOA_FISICA
ORDER BY 
    APV.CD_SETOR_ATENDIMENTO 
--FETCH FIRST 1 ROWS ONLY